name: Generate images.json

on:
  push:
    branches:
      - main  # si attiva a ogni push su "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate images.json
        run: |
          node generate-json.js

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update images.json"
          git push
